version: '3.9'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: your_project_name
        container_name: MatchApi
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:1.21.6
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:8.0.28
        platform: linux/amd64
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: match_api
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network

    db_test:
        image: mysql:8.0.28
        platform: linux/amd64
        hostname: db_test
        container_name: db_test
        restart: unless-stopped
        tty: true
        ports:
            - "33062:3306"
        environment:
            MYSQL_DATABASE: match_api_test
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_WAIT_TIMEOUT: 28800
            MYSQL_MAX_ALLOWED_PACKET: 64M
        volumes:
            - dbtestdata:/var/lib/mysql/
        networks:
            - app-network
        command: mysqld --innodb_use_native_aio=0

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    dbtestdata:
        driver: local
