<?php

namespace Tests\Feature;

use Database\Factories\UserFactory;
use Illuminate\Foundation\Testing\WithFaker;
use PDO;
use Tests\TestCase;
use Faker\Factory as FakerFactory;


class AuthControllerTest extends TestCase
{
    use WithFaker;
    private $user;
    private string $password;

    protected function setUp(): void
    {
        parent::setUp();
        $this->password = 'password123';
        $this->user = (new UserFactory(FakerFactory::create(), $this->pdoInstance))->createAndPersist(['password' => $this->password]);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_register()
    {
        $userData = [
            'name' => $this->faker->name,
            'email' => $this->faker->unique()->safeEmail,
            'password' => 'password123',
            'password_confirmation' => 'password123',
        ];

        $response = $this->postJson(route('register'), $userData);

        $response->assertStatus(201)
            ->assertJsonStructure([
                'data' => [
                    'id',
                    'name',
                    'email',
                    'created_at',
                    'updated_at',
                ],
            ]);
    }

    public function test_login()
    {
        $response = $this->postJson(route('login'), [
            'email' => $this->user->getEmail(),
            'password' => $this->password,
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    'access_token',
                ],
            ]);
    }

    public function test_logout()
    {
        $response = $this->actingAs($this->user, 'api')->postJson(route('logout'));

        $response->assertStatus(200)
            ->assertJson([
                'data' => [
                    'message' => 'Logged out successfully.',
                ],
            ]);
    }
}
