<?php

namespace Tests\Feature\Http\Controllers;

use App\Domain\Location\Repositories\LocationRepositoryInterface;
use Database\Factories\UserFactory;
use Faker\Factory as FakerFactory;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LocationControllerTest extends TestCase
{
    use WithFaker;

    private LocationRepositoryInterface $locationRepository;

    protected function setUp(): void
    {
        parent::setUp();
        $this->locationRepository = $this->app->make(LocationRepositoryInterface::class);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testUpdateLocation(): void
    {
        $user = (new UserFactory(FakerFactory::create(), $this->pdoInstance))->createAndPersist(['password' => '1234']);
        $token = $this->authenticateUser($user,'1234');

        $latitude = $this->faker->latitude;
        $longitude = $this->faker->longitude;

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $token,
        ])->putJson('/api/location', [
            'latitude' => $latitude,
            'longitude' => $longitude,
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure([
            'data' => [
                'id',
                'user_id',
                'latitude',
                'longitude',
            ]
        ]);

        $responseData = $response->json('data');
        $this->assertEquals($user->getId(), $responseData['user_id']);
        $this->assertEquals($latitude, $responseData['latitude']);
        $this->assertEquals($longitude, $responseData['longitude']);
    }

    private function authenticateUser($user, $password)
    {
        $response = $this->postJson('/api/login', [
            'email' => $user->getEmail(),
            'password' => $password, // これは createUser メソッドで設定したパスワードと同じにしてください。
        ]);

        $response->assertStatus(200);

        return $response->json('data.access_token');
    }
}
