<?php

namespace Tests\Feature\Http\Controllers;

use App\Domain\ProfileImage\Services\ProfileImageService;
use App\Domain\User\Services\UserService;
use Database\Factories\UserFactory;
use Faker\Factory as FakerFactory;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
use Tymon\JWTAuth\Facades\JWTAuth;

class ProfileImageControllerTest extends TestCase
{
    private UserService $userService;
    private ProfileImageService $profileImageService;

    protected function setUp(): void
    {
        parent::setUp();
        $this->userService = $this->app->make(UserService::class);
        $this->profileImageService = $this->app->make(ProfileImageService::class);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_upload()
    {
        $user = (new UserFactory(FakerFactory::create(), $this->pdoInstance))->createAndPersist(['password' => '1234']);
        $token = JWTAuth::fromUser($user);
        $file = UploadedFile::fake()->image('profile.jpg');

        $response = $this->withHeader('Authorization', "Bearer $token")
            ->post('/api/user/profile-image', ['image' => $file]);

        $response->assertStatus(200)
            ->assertJson(['message' => '画像がアップロードされました。']);
    }

    public function test_upload_and_delete_profile_image()
    {
        $user = (new UserFactory(FakerFactory::create(), $this->pdoInstance))->createAndPersist(['password' => '1234']);
        $token = JWTAuth::fromUser($user);

        // Upload the image
        $file = UploadedFile::fake()->image('profile.jpg');
        $uploadResponse = $this->withHeader('Authorization', "Bearer $token")
            ->post('/api/user/profile-image', ['image' => $file]);

        $uploadResponse->assertStatus(200);

        // Get the uploaded profile image
        $profileImage = DB::table('profile_images')->first();

        $response = $this->withHeader('Authorization', "Bearer $token")
            ->delete('/api/user/profile-image/' . $profileImage->id);
        $response->assertStatus(200)
            ->assertJson([
                'message' => '画像が削除されました。'
            ]);
    }
}
